version: "3.9"

services:
  logger:
    build:
      context: ./src/services/logger
    volumes:
      - ./log-output:/var/log/logger
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - LOG_FORMAT=[{time}] [{level}] [{message}]
      - LOG_INTERVAL_SECONDS=3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://logger:8000    
    depends_on:
      - logger
