version: "3.9"

services:
  centrifugo:
    image: centrifugo/centrifugo:v6
    container_name: centrifugo_server
    ports:
      - "8000:8000"
    volumes:
      - ./src/services/collector/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    networks:
      - app_network

  log-generator:
    build:
      context: ./src/services/generator
    volumes:
      - ./logs:/var/log/logger  
    environment:
      - LOG_RATE=10
      - CONSOLE_OUTPUT=true
      - OUTPUT_FILE=/var/log/logger/service.log
      - LOG_FORMAT=json
      - ENABLE_BURSTS=true
      - BURST_FREQUENCY=0.1
      - BURST_MULTIPLIER=5
      - BURST_DURATION=3
    ports:
      - "8080:8000"
    networks:
      - app_network
    restart: unless-stopped

  log-collector:
    build:
      context: ./src/services/collector
      dockerfile: Dockerfile
    container_name: log_collector
    volumes:
      - ./logs:/app/logs         # Mount same ./logs dir for collector
      - ./src/services/collector/config.yml:/app/config.yml:ro
    depends_on:
      - centrifugo
      - log-generator
    networks:
      - app_network
    ports:
      - "8081:8080"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://log-generator:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/connection/websocket
    depends_on:
      - log-generator
      - centrifugo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
