version: "3.9"

services:
  storage: 
    build:
      context: ./src/services/storage
    volumes:
      - ./parsed_logs:/var/log/data/parsed
      - ./storage_logs:/var/log/data/storage
    environment:
      - NATS_URL=nats://nats_server:4222
    command: ./storage --input-dir /var/log/data/parsed --storage-dir /var/log/data/storage --rotation-size 1 --rotation-hours 1 --interval 5
    depends_on:
      - parser

  nats:
    image: nats:latest
    container_name: nats_server
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app_network
    restart: unless-stopped
  parser:
    build:
      context: ./src/services/parser
      dockerfile: Dockerfile
    container_name: log_parser
    environment:
      - NATS_URL=nats://nats_server:4222
      - OUTPUT_DIR=/var/log/data/parsed
      - OUTPUT_FILE=/var/log/data/parsed/parsed.log

    volumes:
      - ./parsed_logs:/var/log/data/parsed 
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - nats

  centrifugo:
    image: centrifugo/centrifugo:v6
    container_name: centrifugo_server
    ports:
      - "8000:8000"
    volumes:
      - ./src/services/collector/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    networks:
      - app_network

  log-generator:
    build:
      context: ./src/services/generator
    volumes:
      - ./logs:/var/log/logger  
    environment:
      - LOG_RATE=10
      - CONSOLE_OUTPUT=true
      - OUTPUT_FILE=/var/log/logger/service.log
      - LOG_FORMAT=json
      - ENABLE_BURSTS=true
      - BURST_FREQUENCY=0.1
      - BURST_MULTIPLIER=5
      - BURST_DURATION=3
    ports:
      - "8080:8000"
    networks:
      - app_network
    restart: unless-stopped

  log-collector:
    build:
      context: ./src/services/collector
      dockerfile: Dockerfile
    container_name: log_collector
    volumes:
      - ./logs:/app/logs       
      - ./src/services/collector/config.yml:/app/config.yml:ro
    depends_on:
      - centrifugo
      - log-generator
      - nats
    networks:
      - app_network
    environment:
      - NATS_URL=nats://nats_server:4222
    ports:
      - "8081:8080"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GENERATOR_API_URL=http://localhost:8080
      - NEXT_PUBLIC_COLLECTOR_API_URL=http://localhost:8081
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/connection/websocket
    depends_on:
      - log-generator
      - centrifugo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
