version: "3.9"

services:

  log-generator:
    build:
      context: ./src/services/logger
    volumes:
      - ./src/services/logger:/app
      - ./logs:/var/log/logger
    environment:
      - LOG_RATE=10
      - CONSOLE_OUTPUT=true
      - OUTPUT_FILE=./logs/service.log
      - LOG_FORMAT=json
      - ENABLE_BURSTS=true
      - BURST_FREQUENCY=0.1
      - BURST_MULTIPLIER=5
      - BURST_DURATION=3
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://log-generator:8000    
    depends_on:
      - log-generator
