version: "3.9"

services:

  log-generator:
    build:
      context: ./src/services/logger
    volumes:
      - ./src/services/logger:/app
      - ./logs:/var/log/logger
    environment:
      - LOG_RATE=10
      - CONSOLE_OUTPUT=true
      - OUTPUT_FILE=/var/log/logger/service.log

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://logger:8000    
    depends_on:
      - log-generator
