log_files:
  - /app/logs/service.log
check_interval: 0.5
centrifugo:
  url: http://centrifugo:8000
  api_key: jM-Ot3ZBVJcKOu8yzI3l7iK7yByulGjpwWtBUe2zcIbsaFPYWY4b6c7MCkspaFrKOCmTnJPDSeOw6AUqUCInzg
channel_id: logs
